SgqSystem/Controllers/UserAndRoles/UserSgqController.cs
using Dominio;
using Dominio.Interfaces.Services;
using DTO.DTO;
using DTO.DTO.Params;
using DTO.Helpers;
using Helper;
using SgqSystem.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SgqSystem.Secirity;
using DTO;

namespace SgqSystem.Controllers
{
    [CustomAuthorize]
    public class UserSgqController : BaseController
    {
        private SgqDbDevEntities db = new SgqDbDevEntities();

        private IBaseDomain<ParCompany, ParCompanyDTO> _baseDomainParCompany;
        private IBaseDomain<ParCompanyXUserSgq, ParCompanyXUserSgqDTO> _baseDomainParCompanyXUserSgq;
        private IBaseDomain<UserSgq, UserDTO> _baseDomainUserSgq;
        private IBaseDomain<RoleUserSgq, RoleUserSgqDTO> _baseDomainRoleUserSGQ;

        public UserSgqController(IBaseDomain<ParCompany, ParCompanyDTO> baseDomainParCompany,
            IBaseDomain<ParCompanyXUserSgq, ParCompanyXUserSgqDTO> baseDomainParCompanyXUserSgq,
            IBaseDomain<UserSgq, UserDTO> baseDomainUserSgq,
            IBaseDomain<RoleUserSgq, RoleUserSgqDTO> baseDomainRoleUserSGQ
            )
        {
            _baseDomainParCompany = baseDomainParCompany;
            _baseDomainUserSgq = baseDomainUserSgq;
            _baseDomainParCompanyXUserSgq = baseDomainParCompanyXUserSgq;
            _baseDomainRoleUserSGQ = baseDomainRoleUserSGQ;

            ViewBag.listaParCompany = _baseDomainParCompany.GetAll();
            var listaRoleSGQ = _baseDomainRoleUserSGQ.GetAll();

            foreach (var roleSgq in listaRoleSGQ)
                roleSgq.Name = roleSgq.Name.Trim();

            ViewBag.listaRoleSGQ = listaRoleSGQ;
        }

        // GET: UserSgq
        public ActionResult Index()
        {
            return View(_baseDomainUserSgq.GetAllNoLazyLoad().ToList());
        }

        // GET: UserSgq/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserSgq userSgq = db.UserSgq.Find(id);
            if (userSgq == null)
            {
                return HttpNotFound();
            }
            return View(userSgq);
        }

        /// <summary>
        /// Tela de Perfil Usuário
        /// </summary>
        /// <param name="motivo">Quando obtiver um motivo, é por cause da expiração da senha</param>
        /// <returns></returns>
        [FilterUnit(filtraUnidadeDoUsuario = false)]
        public ActionResult Perfil(string motivo = "")
        {
            ViewBag.Title = "Perfil";

            ViewBag.Motivo = motivo;

            var idUsuario = Guard.GetUsuarioLogado_Id(ControllerContext.HttpContext);

            var userSgq = db.UserSgq.Where(x => x.Id == idUsuario).FirstOrDefault();

            List<ParCompanyXUserSgq> parCompanyXUserSgq = db.ParCompanyXUserSgq.Where(x => x.UserSgq_Id == idUsuario).ToList();

            var model = new UserViewModel()
            {
                Id = userSgq.Id,
                Name = userSgq.Name,
                FullName = userSgq.FullName,
                Email = userSgq.Email,
                Roles = userSgq.Role == null ? new string[0] : userSgq.Role.Split(','),
                Password = userSgq.Password,
                Phone = userSgq.Phone,
                ParCompany_Id = userSgq.ParCompany_Id,
                Empresa = parCompanyXUserSgq != null ? (from comp in parCompanyXUserSgq select new EmpresaDTO { Role = comp.Role, Nome = comp.ParCompany.Name }).ToList() : new List<EmpresaDTO>()
            };

            return View(model);
        }

        // GET: UserSgq/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserSgq/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public bool Save(UserDTO userSgqDto)
        {
            var IsActive = userSgqDto.IsActive;

            ValidaUserSgqDto(userSgqDto);

            if (!ModelState.IsValid)
                return false;

            //Se for Estados Unidos ou Canada e for um novo usuário
            if ((DTO.GlobalConfig.Eua == true || DTO.GlobalConfig.Canada == true) && userSgqDto.Id == 0)
            {
                if ((userSgqDto.Password == "") || (userSgqDto.Password == null))
                    userSgqDto.Password = "USERUSA";
            }

            userSgqDto.ParCompany_Id = userSgqDto.ListParCompany_Id.FirstOrDefault();
            if (userSgqDto.Id == 0)
            {
                userSgqDto.AddDate = DateTime.Now;
                userSgqDto.Password = Guard.EncryptStringAES(userSgqDto.Password);
                IsActive = true;
            }
            else
            {
                userSgqDto.AlterDate = DateTime.Now;

                if (userSgqDto.Password == null)
                {
                    UserSgq dummy = db.UserSgq.Find(userSgqDto.Id);
                    userSgqDto.Password = dummy.Password;
                }
                else
                {
                    userSgqDto.Password = Guard.EncryptStringAES(userSgqDto.Password);
                }
            }

            /*Roles*/
            if (userSgqDto.ListRole != null)
            {
                string roles = string.Join(",", userSgqDto.ListRole);
                userSgqDto.Role = roles;
            }

            var ListParCompany_Id = userSgqDto.ListParCompany_Id;
            userSgqDto = _baseDomainUserSgq.AddOrUpdate(userSgqDto, true);

            /*Adiciona*/
            foreach (var i in ListParCompany_Id)
            {
                var lista = db.ParCompanyXUserSgq.Where(r => r.ParCompany_Id == i && r.UserSgq_Id == userSgqDto.Id).ToList();
                if (lista.Count == 0)
                {
                    _baseDomainParCompanyXUserSgq.AddOrUpdate(new ParCompanyXUserSgqDTO() { Id = 0, UserSgq_Id = userSgqDto.Id, ParCompany_Id = i }, true);
                }
            }

            /*Remove*/
            foreach (var i in db.ParCompanyXUserSgq.Where(r => r.UserSgq_Id == userSgqDto.Id))
            {
                var lista = ListParCompany_Id.Where(r => r == i.ParCompany_Id).ToList();
                if (lista.Count == 0)
                {
                    //_baseDomainParCompanyXUserSgq.ExecuteSql("DELETE FROM ParCompanyXUserSgq WHERE UserSgq_Id = " + userSgqDto.Id);
                    _baseDomainParCompanyXUserSgq.ExecuteSql("DELETE FROM ParCompanyXUserSgq WHERE UserSgq_Id = " + userSgqDto.Id + " AND ParCompany_Id = " + i.ParCompany_Id);
                }

            }


            if (userSgqDto != null)
                if (GlobalConfig.Eua)
                {
                    var ativo = IsActive ? "1" : "0";
                    var ativoQuery = "UPDATE UserSgq SET IsActive = " + ativo + " WHERE Id = " + userSgqDto.Id + " SELECT IsActive FROM usersgq WHERE Id = " + userSgqDto.Id;
                    var estadoAtual = db.Database.SqlQuery<bool>(ativoQuery).FirstOrDefault();
                }

            /////*Empresas do usuario*/
            //_baseDomainParCompanyXUserSgq.ExecuteSql("DELETE FROM ParCompanyXUserSgq WHERE UserSgq_Id = " + userSgqDto.Id);
            //if (ListParCompany_Id != null)
            //    foreach (int ParCompany_id in ListParCompany_Id)
            //        _baseDomainParCompanyXUserSgq.AddOrUpdate(new ParCompanyXUserSgqDTO() { Id = 0, UserSgq_Id = userSgqDto.Id, ParCompany_Id = ParCompany_id }, true);

            return true;

        }

        // GET: UserSgq/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDTO userSgq = _baseDomainUserSgq.GetById(id.GetValueOrDefault());
            if (userSgq == null)
            {
                return HttpNotFound();
            }
            //if (userSgq != null)
            //    if (GlobalConfig.Eua)
            //    {
            //        userSgq.IsActive = db.Database.SqlQuery<bool>("SELECT IsActive FROM usersgq WHERE Id = " + userSgq.Id).FirstOrDefault();
            //    }

            return View();
        }

        // GET: UserSgq/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserSgq userSgq = db.UserSgq.Find(id);
            if (userSgq == null)
            {
                return HttpNotFound();
            }
            return View(userSgq);
        }

        // POST: UserSgq/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserSgq userSgq = db.UserSgq.Find(id);
            db.UserSgq.Remove(userSgq);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public void ResetSessionTimer()
        {
            try
            {
                HttpCookie currentUserCookie = Request.Cookies["webControlCookie"];
                if (currentUserCookie != null)
                {
                    currentUserCookie.Expires = DateTime.Now.AddHours(48);
                    Response.SetCookie(currentUserCookie);
                }
            }
            catch (Exception)
            {
            }
        }

        [HttpPost]
        public bool VerificarCookieExiste()
        {
            try
            {
                HttpCookie currentUserCookie = Request.Cookies["webControlCookie"];
                if (currentUserCookie != null)
                {

SgqSystem/Views/UserSgq/Create.cshtml
@model Dominio.UserSgq
@{
    ViewBag.Title = Resources.Resource.new_user;
}

<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="@Url.Action("Index", "Home")">Home</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="@Url.Action("Index", "UserSgq")">@Resources.Resource.users</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <span>@Resources.Resource._novo</span>
                </li>
            </ul>
            <div class="page-toolbar">
                <!--<div id="dashboard-report-range" class="pull-right tooltips btn btn-fit-height green" data-placement="top" data-original-title="Change dashboard date range">-->
                @*<div id="dashboard-report-range" class="pull-right tooltips btn btn-fit-height green">
                        <i class="fa fa-calendar"></i>&nbsp;
                        <span class="thin uppercase" id="currentDate"></span>&nbsp;
                    </div>*@
            </div>
        </div>
        <!-- END PAGE BAR -->
        <!-- END PAGE HEADER-->
        <div class="row">
            <div class="col-xs-12">
                <div class="portlet light bordered">
                    <div class="portlet-title tabbable-line">
                        <div class="caption">
                            <i class="icon-share font-dark"></i>
                            <span class="caption-subject font-dark bold uppercase">@Resources.Resource.new_user</span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="tab-content">

                            <div class="tab-pane active" id="setup_tab">
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                        @Html.HiddenFor(r => r.Id)

                                        <div class="form-group">
                                            @Html.Label(Resources.Resource.fullname, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.Editor("userSgqDto.FullName", new { htmlAttributes = new { @class = "form-control" } })
                                            </div>
                                        </div>

                                        @*<div class="form-group hide">
                                                @Html.Label(Resources.Resource.date, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.Editor("userSgqDto.AccessDate", new { htmlAttributes = new { @class = "form-control" } })
                                                </div>
                                            </div>

                                            <div class="form-group hide">
                                                <div class="col-md-10">
                                                    @Html.Editor("userSgqDto.AddDate", new { htmlAttributes = new { @class = "form-control" } })
                                                </div>
                                            </div>

                                            <div class="form-group hide">
                                                <div class="col-md-10">
                                                    @Html.Editor("userSgqDto.AlterDate", new { htmlAttributes = new { @class = "form-control" } })
                                                </div>
                                            </div>*@

                                        <div class="form-group">
                                            @Html.Label(Resources.Resource.email, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.Editor("userSgqDto.Email", new { htmlAttributes = new { @class = "form-control", @type = "email" } })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.Label(Resources.Resource.phone, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.Editor("userSgqDto.Phone", new { htmlAttributes = new { @class = "form-control" } })
                                            </div>
                                        </div>

                                        @*<div class="form-group">
                                                @Html.Label(Resources.Resource.default_company, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.DropDownList("userSgqDto.ParCompany_Id", new SelectList(ViewBag.listaParCompany, "Id", "Name"), new { @class = "form-control" })
                                                </div>
                                            </div>*@

                                        <div class="form-group">
                                            @Html.Label(Resources.Resource.company, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.DropDownList("userSgqDto.ListParCompany_Id", new SelectList(ViewBag.listaParCompany, "Id", "Name"), new { @class = "form-control required", required = "required" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.Label(Resources.Resource.role, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.DropDownList("userSgqDto.ListRole", new SelectList(ViewBag.listaRoleSGQ, "Name", "Name"), new { @class = "form-control" })
                                            </div>
                                        </div>

                                        <hr />

                                        @if (@DTO.GlobalConfig.Eua)
                                        {
                                            <div class="form-group">
                                                @Html.Label(Resources.Resource.use_active_directory, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    <input id="userSgqDto_UseActiveDirectory" name="userSgqDto.UseActiveDirectory" type="checkbox" value="">
                                                </div>
                                            </div>
                                        }

                                        <div class="form-group">
                                            @Html.Label(Resources.Resource.username, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.Editor("userSgqDto.Name", new { htmlAttributes = new { @class = "form-control" } })
                                            </div>
                                        </div>

                                        <div id="passwordContainer">
                                            <div class="form-group">
                                                @Html.Label(Resources.Resource.password, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.Editor("userSgqDto.Password", new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                                                    @*<span id="errMsg"></span>*@
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                @Html.Label(Resources.Resource.confirm_password, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.Editor("userSgqDto.ConfirmPassword", new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <button type="button" id="btnSave" class="btn btn-primary">@Resources.Resource.save</button>
                                                @Html.ActionLink(Resources.Resource.back_to_list, "Index", null, new { @class = "btn btn-default" })
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- END CONTENT BODY -->
</div>

<script>

    $(".sidebar-toggler").removeClass("hide");
    $(".page-sidebar-wrapper").removeClass("hide");
    navbarSelect("navbar15");

    $('#userSgqDto_AddDate').val(new Date($.now()).toUTCString());

    $(document).on('switchChange.bootstrapSwitch', '#userSgqDto_UseActiveDirectory', function () {
        $(this).is(":checked") ? $('#userSgqDto_UseActiveDirectory').val(true) : $('#userSgqDto_UseActiveDirectory').val(false)
        setupAD();
    });

    function setupAD() {
        if ($('#userSgqDto_UseActiveDirectory').length > 0) {
            if ($('#userSgqDto_UseActiveDirectory').prop('checked')) {
                $('#passwordContainer').addClass('hide');
            } else {
                $('#passwordContainer').removeClass('hide');
            }
        }
    }

    $(document).on("click", "#btnSave", function () {

        var valid = true;

        if ($("#userSgqDto_FullName").val() == "") {
            openMessageModal(Resources('fullname_required'), '');
            return;
        }

        if ($("#userSgqDto_Name").val() == "") {
            openMessageModal(Resources('username_required'), '');
            return;
        }

        if ($("#userSgqDto_ListParCompany_Id").val().length == 0) {
            openMessageModal(Resources('select_one_company'), '');
            return;
        }

        if (!$('#passwordContainer').hasClass('hide')) {
            if ($("#userSgqDto_Password").val() == "") {
                openMessageModal(Resources('password_required'), '');
                return;
            }

            if ($("#userSgqDto_Password").val() != $("#userSgqDto_ConfirmPassword").val()) {
                openMessageModal(Resources('invalid_password'), '');
                return;
            }
        }

        $.post("@Url.Action("Save", "UserSgq")", $('form').serializeObject(), function (data) {

            if (data == "True") {
                openMessageModal(Resources('user_save_success'), '');
            } else {
                openMessageModal(Resources('repeated_username'), '');
            }

        })
    });

    $(document).ready(function () {
        $.fn.bootstrapSwitch.defaults.size = 'small';
        $.fn.bootstrapSwitch.defaults.onText = '@Resources.Resource.yes';
        $.fn.bootstrapSwitch.defaults.offText = '@Resources.Resource.no';
        $("[type='checkbox']").bootstrapSwitch();

        $("#userSgqDto_ListParCompany_Id").attr("multiple", "multiple");
        $("#userSgqDto_ListParCompany_Id").select2();

        $("#userSgqDto_ListRole").attr("multiple", "multiple");
        $("#userSgqDto_ListRole").select2();

        $("#userSgqDto_UseActiveDirectory").prop('checked', true);
        $("#userSgqDto_UseActiveDirectory").trigger("change");

        //setupAD();

    });

</script>

<script>
    $(document).ready(function () {
        closeLeftSidebar();
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SgqSystem/Views/UserSgq/Delete.cshtml
@model Dominio.UserSgq

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserSgq</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AcessDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AcessDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlterDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlterDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParCompany_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParCompany_Id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink(Resources.Resource.back_to_list, "Index")
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        closeLeftSidebar();
    });
</script>

SgqSystem/Views/UserSgq/Details.cshtml
@model Dominio.UserSgq

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserSgq</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AcessDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AcessDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlterDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlterDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParCompany_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParCompany_Id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(Resources.Resource.edit, "Edit", new { id = Model.Id }) |
    @Html.ActionLink(Resources.Resource.back_to_list, "Index")
</p>

<script>
    $(document).ready(function () {
        closeLeftSidebar();
    });
</script>